### ISSUE TITLE
OpenSSL issues when cross-compiling msal-rust for arm

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [sangonzal/msal-rust#1]
Hello,

Just been having grief cross-compiling this module for arm (got linker errors saying SSL_library_init was undefined).
That turned out to be due to the way reqwest was configured. 
This is what I did to get things compiling:

```
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -7,7 +7,9 @@ edition = "2018"
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
-reqwest = { version = "0.10", features = ["json", "blocking"] }
+reqwest = { version = "0.10", default-features=false, features = ["json", "blocking", "rustls-tls"] }
+openssl = { version = "0.10.32", features = ["vendored"] }
+
 tokio = { version = "0.2", features = ["full"] }
 url = "2.1.1"
 serde = { version = "1.0", features = ["derive"] }
```
(You might want to double check this is correct, but could save the next person a few days of pulling out their hair).

**Comment by sangonzal** [comment]
Thanks @marcbrevoort-cyberhive! 

Leaving this note here as an FYI for anyone else who finds this project - Please note that this was a hackathon project used to learn a bit about the language, and it has not been tested and it does not follow (most?) Rust conventions, so it should not be used in a production setting. At most it might be able to be used as a reference to bootstrap your own client code to interact with Azure Active Directory via the OAuth2.0 protocol.
